name: Make Canary Release

on:
  push:
    branches:
      - 'canary'
    paths:
      - '.github/edit2MakeNewCanary'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Source Code Download
      run: git clone --branch canary --single-branch --recurse-submodules https://github.com/siavash79/AOSPMods.git .
      
    - name: JDK 17 Setup
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
        
    - name: Shell Scripts Permissions
      run: chmod +x .github/*.sh

    - name: Changelog Generation
      run: .github/extractChanges.sh

    - name: Version Bump
      run: .github/bumpVersion.sh ${{ github.run_id }}

    - name: Gradlew Permissions
      run: chmod +x gradlew
      
    - name: Gradle Build
      run: ./gradlew assembleRelease

    - uses: r0adkll/sign-android-release@v1
      name: APK Signature
      id: sign_app
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
      env:
        BUILD_TOOLS_VERSION: "33.0.0"
          
    - name: Magisk Module Generation
      run: .github/make_zip.sh

    - name: Upload Xposed Artifact to Actions
      uses: actions/upload-artifact@v2
      with: 
        name: AOSPMods_Xposed.zip
        path: output

    - name: Upload Full Artifact to Actions
      uses: actions/upload-artifact@v2
      with:
        name: AOSPMods_Full.zip
        path: output

    - name: Previous Release Deletion
      continue-on-error: true
      run: gh release delete canary_builds -y -R siavash79/AOSPMods
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Canary Binary Release
      uses: Hs1r1us/Release-AIO@v1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: 'canary_builds'
        release_name: 'Latest Canary'
        body: 'Caution: The source code assets are not associated with the zip files'
        prerelease: true
        draft: false
        asset_files: 'output'

    - name: Version Bump Commit
      uses: github-actions-x/commit@v2.9
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'canary'
        commit-message: 'Version update: Release'
        force-add: 'true'
        files: MagiskModBase/module.prop app/build.gradle latestVersion.json CanaryChangelog.md latestCanary.json MagiskModuleUpdate_Xposed.json MagiskModuleUpdate_Full.json
        name: GitHub
        email: aospmods@siava.sh

    - name: Telegram Channel Post
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.AOSPMODS_CHANNEL_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: ${{ env.TMessage }}
        format: markdown

    - name: Telegram File Attachment
      run: |
        curl -v "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMediaGroup?chat_id=${{ secrets.AOSPMODS_CHANNEL_ID }}&media=%5B%7B%22type%22%3A%22document%22%2C%20%22media%22%3A%22attach%3A%2F%2FXposed%22%7D%2C%7B%22type%22%3A%22document%22%2C%20%22media%22%3A%22attach%3A%2F%2FFull%22%7D%5D" -F Xposed="@output/AOSPMods_Xposed.zip" -F Full="@output/AOSPMods_Full.zip"